### ISSUE TITLE
Document how to add finding aid PDFs and EADs so they are downloadable

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#642]
As noted in #640, there are several requirements/conventions that need to be followed for a collection PDF or EAD file to be made available to be downloaded by users. The process is not too hard but certainly not self-explanatory, so we should document this somewhere.

For background, here's part of #640 I'll also include here:

We added a feature that enables us to present links for downloading a collection PDF or EAD if one or both of those files have been named and stored appropriately. More specifically, based on comments by the developer who worked on ticket #371 I think the following rules apply:

- A finding aid PDF has to be named `unitid.pdf`, where `unitid` is the collection ID, I assume
- A finding aid EAD has to be named `unitid.xml`
- If either of those files exist and are intended for users to download, they need to be placed in the `public/documents` directory

Also, based on comments in PR #425, which closed #371, I think these other rules might apply:

- If either a PDF or EAD is intended to be downloadable, it needs to also be documented in a `/config/downloads.yml` file like this:

```
sample_unitid:
  pdf:
    href: 'http://example.com/sample.pdf'
    size: '1.23MB'
  ead:
    href: 'http://example.com/sample.xml'
    size: 123456
```
