### ISSUE TITLE
Generate a request submitted to Aeon's external request endpoint (single items)

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#650]
**Acceptance criteria**

Given a repository with a properly configured Aeon instance (see #641 and #647), I should be able to generate a single-item request for a given component using the request button. Clicking the form should pass information off to Aeon's [external request endpoint](https://support.atlas-sys.com/hc/en-us/articles/360011820054-External-Request-Endpoint) where a user can login and complete the request.

* [ ] Implement mapping configuration in #647, supporting both accessors and static values
* [ ] For multivalued fields, join values with `"; "` and return a string
* [ ] Generate the necessary form elements described in the [Aeon docs](https://support.atlas-sys.com/hc/en-us/articles/360011820054-External-Request-Endpoint) and in [@sdellis's comment](https://github.com/projectblacklight/arclight/issues/650#issuecomment-526307924) from mappings set in configuration
* [ ] Clicking the request button should send the request to the Aeon instance via a `POST` request to `$aeon_web_url/aeon.dll?Action=11&Type=200`

**Out of scope**

* Logic to determine what's requestable (see #728)
* Handling multiple items per request (see #729) 

<details><summary>Example</summary>
If I define a configuration as follows (mockup only):

```yaml
request_type: aeon_external_request_endpoint
aeon_external_request_endpoint:
  aeon_web_url: https://example.com/aeon/aeon.dll
  aeon_ere_mapping:
    SystemId: "ArcLight" # static value
    ItemTitle: collection_title # this is an accessor
    ItemSubTitle: component_title # this is an accessor
    ItemVolume: component_box # accessor
    ItemInfo1: "manuscript" # this is a static value
```

And assuming the following:

```json
{
  "collection_title": "Letters of Thomas Jefferson",
  "component_title": "1789 ALS",
  "component_box": "Box 1"
}
```

I should see a form like the following:

```html
<form action="http://example.com/aeon/aeon.dll?Action=11&Type=200" method="post">
	<input type="hidden" name="SystemID" value="ArcLight">
	<input type="hidden" name="ItemTitle" value="Letters of Thomas Jefferson">
	<input type="hidden" name="ItemSubtitle" value="1789 ALS">
	<input type="hidden" name="ItemVolume" value="Box 1">
	<input type="hidden" name="ItemInfo1" value="manuscript">
	<input type="submit" value="Request">
</form>
```
</details>

<details><summary>TO DETERMINE (completed)</summary>

* [x] Do we need to do anything specific to associate the request with that specific component? 
* [x] What is the correct URL to send a POST request to?
* [x] What information other than what's listed in #647 needs to be sent as part of the request? (Examples: date of visit, notes/comments, Aeon request grouping configuration? Or can these be handled downstream by Aeon?)
</details>
