### ISSUE TITLE
Mappings for Aeon OpenURL-based requests

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#651]
**Acceptance criteria**

Given a repository with a configured Aeon instance, provide the ability to define mappings for that repository for OpenURL parameters from information in an ArcLight collection/component or some other method (e.g. a function that generates values). The mappings should be configurable per repository, as they may vary across each.

* [x] Create list of fields (see #647 as an example)
  * decision: We won't provide a comprehensive list of fields or validate them; this would be on Aeon implementers:
* [ ] Implement mapping configuration along something like the following, supporting both accessors and static values:
* [ ] For multivalued fields, join values with `"; "` and return a string

<details><summary>mockup</summary>

```yaml
aeon_openurl:
  aeon_web_url: https://example.com/aeon/aeon.dll
  open_url_mapping:
    rft.title: title # this is an accessor
    rft.au: creator # this is an accessor
    rft.genre: "manuscript" # this is a static value
```
</details>
